[package]
name = "aigame"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"
sdl2 = "*"
paste = "*"
unstringify = "0.1.1"